/*
 * Copyright (C) Balena.io - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 *
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import { core } from '@balena/jellyfish-types';

export interface ChannelData {
	/**
	 * Cards matching this filter will be handled by the channel
	 */
	filter: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface ChannelContractDefinition
	extends core.ContractDefinition<ChannelData> {}

export interface ChannelContract extends core.Contract<ChannelData> {}
