docker:
  publish: false
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/jellyfish-sut
      publish: false
      args:
        - BUILDKIT_INLINE_CACHE=1
npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "16"
